# Default values for pipeline-pirates Helm chart
# ---------------------------------------------

replicaCount: 1

image:
  repository: ahmedhusseinabdelkader/pipeline-pirates
  pullPolicy: IfNotPresent
  tag: "v2"

# Backend configuration
backend:
  name: pipeline-pirates-backend
  containerPort: 8000

# Frontend configuration
frontend:
  name: pipeline-pirates-frontend
  containerPort: 80

# Database
db:
  secretName: pipeline-pirates-db-secret

# Redis
redis:
  url: "redis://localhost:6379"

# Image pull secrets (leave empty if public image)
imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

# Service Account
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

# Pod annotations & labels
podAnnotations: {}
podLabels: {}

# Security context
podSecurityContext: {}
securityContext: {}

# Service configuration
service:
  type: ClusterIP
  port: 80

# Resources (important for HPA)
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

# Horizontal Pod Autoscaler (HPA)
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  cpuUtilizationPercentage: 70

# Node scheduling
nodeSelector: {}
tolerations: []
affinity: {}
