apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pipeline-pirates.fullname" . }}
  labels:
    {{- include "pipeline-pirates.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pipeline-pirates.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pipeline-pirates.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          
          # الجزء اللي بيشغل الـ Sign-in/Sign-up ويربطهم بالداتابيز
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secretName }}
                  key: url
            - name: REDIS_URL
              value: {{ .Values.redis.url | quote }}
            - name: ENV
              value: "production"

          ports:
            - name: http
              containerPort: 8000
              protocol: TCP

          # التأكد إن الأبلكيشن شغال قبل ما يبعتله Traffic
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http

          # تحديد الموارد (مهم جداً للـ SRE/Ops)
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
