apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "pipeline-pirates.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
    # دي عشان الـ Sign-up لو بتبعت داتا كبيرة شوية
    nginx.ingress.kubernetes.io/proxy-body-size: "8m" 
spec:
  rules:
    - host: pirates.local  # ده العنوان اللي هنفتحه
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "pipeline-pirates.fullname" . }}
                port:
                  number: 80
