apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name | default (include "pipeline-pirates.fullname" .) }}
  labels:
    {{- include "pipeline-pirates.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pipeline-pirates.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pipeline-pirates.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          # --- Env variables ---
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ default "pipeline-pirates-db-secret" .Values.db.secretName }}
                  key: url
            - name: REDIS_URL
              value: {{ .Values.redis.url | quote }}
            - name: ENV
              value: "production"

          # --- Ports ---
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP

          # --- Probes ---
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http

          # --- Resources ---
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
