apiVersion: v1
kind: Service
metadata:
  name: {{ include "pipeline-pirates.fullname" . }}
  labels:
    {{- include "pipeline-pirates.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80         # البورت اللي الخدمة بتسمع عليه
      targetPort: 8000 # لازم يطابق الـ containerPort اللي في الـ Deployment
      protocol: TCP
      name: http
  selector:
    {{- include "pipeline-pirates.selectorLabels" . | nindent 4 }}
