# بناء الباك إند
    - name: Build and push Backend
      uses: docker/build-push-action@v3
      with:
        context: ./app
        push: true
        tags: ahmedhusseinabdelkader/pipeline-backend:v2

    - name: Build and push Frontend
      uses: docker/build-push-action@v3
      with:
        context: ./frontend
        push: true
        tags: ahmedhusseinabdelkader/pipeline-frontend:v2
